on:
  push:
    branches:
    - main
    - features/**
    tags:
    - '*.*.*'
  pull_request:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@b7821147f564527086410e8edd122d89b4b9602f
      with:
        dotnet-version: '3.1.301'
    - run: dotnet --info
    
    - if: contains(matrix.runs-on, 'macOS') || contains(matrix.runs-on, 'ubuntu')
      run: ./build.sh
    - if: matrix.runs-on == 'windows-latest' && github.ref != 'refs/heads/main' && !contains(github.ref, 'refs/tags/')
      run: ./build.cmd
    - if: (matrix.runs-on == 'windows-latest') && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
      env:
        SignClientSecret: ${{ secrets.SIGNCLIENT }}
      run: |
        ./build.cmd sign
        dotnet nuget push .\artifacts\*.nupkg -s https://www.myget.org/F/identity/api/v2/package -k ${{ secrets.MYGET }}
